# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Spring Boot application JAR file into the container at the specified location
COPY target/calculator-0.0.1-SNAPSHOT.jar /app/

# Specify the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "calculator-0.0.1-SNAPSHOT.jar"]

