name: Deploy to Render.com

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the desired Java version
          distribution: 'adopt'
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Build Spring Boot application
        run: |
          cd calculator
          mvn clean install  # Adjust the build command as needed

      - name: Install Docker
        run: |
          # Remove any previously installed Docker versions
          sudo apt-get remove -y docker docker-engine docker.io containerd runc

          # Install Docker using official Docker script
          curl -fsSL https://get.docker.com | sh

          # Add the GitHub Actions runner user to the docker group
          sudo usermod -aG docker $USER

          # Restart Docker service
          sudo service docker restart

      - name: Log in to Docker Hub
        run: |
          docker login -u theashpandey -p Akp@9145826  # Use your Docker Hub username and password

      - name: Build Docker image
        working-directory: calculator
        run: |
          docker build -t calculator -f Dockerfile.txt .
        
      - name: Tag Docker image
        run: |
          docker tag calculator renderapp/calculator:latest

      - name: Push Docker image to Render.com
        run: |
          docker push renderapp/calculator:latest

      - name: Deploy to Render.com
        run: |
          curl -X POST "https://api.render.com/v1/services/SERVICE_ID/deploys" \
            -H "Authorization: Bearer rnd_ufp75WMgYxd1RuwdVEoa5q6aU0Ut"

