name: Deploy to Render.com

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Remove any previously installed Docker versions
          sudo apt-get remove -y docker docker-engine docker.io containerd runc

          # Install Docker using official Docker script
          curl -fsSL https://get.docker.com | sh

          # Add the GitHub Actions runner user to the docker group
          sudo usermod -aG docker $USER

          # Restart Docker service
          sudo service docker restart

      - name: Log in to Docker Hub
        run: |
          docker login -u theashpandey -p Akp@9145826

      - name: Build Docker image
        working-directory: calculator
        run: |
          docker build -t calculator -f Dockerfile.txt .
        
      - name: Tag Docker image
        run: |
          docker tag calculator theashpandey/calculator:latest

      - name: Push Docker image to Render.com
        run: |
          docker push theashpandey/calculator:latest

      - name: Deploy to Render.com
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cjrnpugjbais73e396i0/deploys" \
            -H "Authorization: Bearer rnd_ufp75WMgYxd1RuwdVEoa5q6aU0Ut"
